# Assignment - 3


# Task : 1

Q1 : Write a function to compute 5/0 and use try/except to catch the exceptions

In [3]:
def division():
    return 5/0

try:
    division()
except ZeroDivisionError:
    print ("division by zero!")
except Exception as e:
    print ('Caught an exception')
finally:
    print ('In finally block for cleanup')

division by zero!
In finally block for cleanup


Q2 : 
 Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"]

In [9]:
subject=["Americans", "Indians"]

verb=["Play", "watch"]

obj=["Baseball","cricket"]

sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
    print(sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


# Task: 2

Q1  Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre  Theophile Vandermonde.

In [11]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [12]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [13]:
x = np.array([1, 2, 3, 5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [14]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])